"""baseline_schema

Revision ID: 466d0c1bcfe2
Revises: 0001
Create Date: 2026-08-03 17:53:28.067450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '466d0c1bcfe2'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anomaly_events', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('anomaly_events', 'dataset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('anomaly_events', 'target_col',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('anomaly_events', 'threshold_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('anomaly_events', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('anomaly_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_anomaly_model'), table_name='anomaly_events')
    op.drop_index(op.f('idx_anomaly_time'), table_name='anomaly_events')
    op.alter_column('forecasts', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('forecasts', 'dataset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('forecasts', 'target_col',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('forecasts', 'run_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('forecasts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('forecasts_time_idx'), table_name='forecasts')
    op.drop_index(op.f('idx_forecasts_dataset_time'), table_name='forecasts')
    op.create_index('idx_forecasts_dataset_time', 'forecasts', ['dataset', 'time'], unique=False)
    op.drop_index(op.f('idx_forecasts_model_time'), table_name='forecasts')
    op.create_index('idx_forecasts_model_time', 'forecasts', ['model_name', 'time'], unique=False)
    op.alter_column('model_registry', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('model_registry', 'version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('model_registry', 'task',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('model_registry', 'architecture',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('model_registry', 'mlflow_run_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('model_registry', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('model_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_registry_task_active'), table_name='model_registry')
    op.drop_constraint(op.f('model_registry_model_name_version_key'), 'model_registry', type_='unique')
    op.create_unique_constraint('uq_model_version', 'model_registry', ['model_name', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_model_version', 'model_registry', type_='unique')
    op.create_unique_constraint(op.f('model_registry_model_name_version_key'), 'model_registry', ['model_name', 'version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_registry_task_active'), 'model_registry', ['task', 'is_active'], unique=False)
    op.alter_column('model_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_registry', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('model_registry', 'mlflow_run_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('model_registry', 'architecture',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('model_registry', 'task',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('model_registry', 'version',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('model_registry', 'model_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('idx_forecasts_model_time', table_name='forecasts')
    op.create_index(op.f('idx_forecasts_model_time'), 'forecasts', ['model_name', sa.literal_column('time DESC')], unique=False)
    op.drop_index('idx_forecasts_dataset_time', table_name='forecasts')
    op.create_index(op.f('idx_forecasts_dataset_time'), 'forecasts', ['dataset', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('forecasts_time_idx'), 'forecasts', [sa.literal_column('time DESC')], unique=False)
    op.alter_column('forecasts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('forecasts', 'run_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('forecasts', 'target_col',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('forecasts', 'dataset',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('forecasts', 'model_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_anomaly_time'), 'anomaly_events', [sa.literal_column('start_time DESC')], unique=False)
    op.create_index(op.f('idx_anomaly_model'), 'anomaly_events', ['model_name', sa.literal_column('start_time DESC')], unique=False)
    op.alter_column('anomaly_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('anomaly_events', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('anomaly_events', 'threshold_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('anomaly_events', 'target_col',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('anomaly_events', 'dataset',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('anomaly_events', 'model_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
